//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181118.1&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///	//单人使命 PVP 金碟游乐场
        ///	&quot;2334&quot;: {
        ///	 &quot;name&quot;: &quot;Recondition the Anima&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;3088&quot;: {
        ///	 &quot;name&quot;: &quot;Recall of Duty&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;167&quot;: {
        ///	 &quot;name&quot;: &quot;a Spectacle for the Ages&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;173&quot;: {
        ///	 &quot;name&quot;: &quot;a Bloody Reunion&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;179&quot;: {
        ///	 &quot;name&quot;: &quot;the Aqua [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_EN_US {
            get {
                return ResourceManager.GetString("Data_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181118.1&quot;, 
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///	//单人使命 PVP 金碟游乐场
        ///	&quot;2334&quot;: {
        ///	 &quot;name&quot;: &quot;Un nouvel épanouissement&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;3088&quot;: {
        ///	 &quot;name&quot;: &quot;La ballade des réminiscences&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;167&quot;: {
        ///	 &quot;name&quot;: &quot;La grande manœuvre éorzéenne&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;173&quot;: {
        ///	 &quot;name&quot;: &quot;Course-poursuite dans le laboratoire&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_FR_FR {
            get {
                return ResourceManager.GetString("Data_FR_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181118.1&quot;, 
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///	//单人使命 PVP 金碟游乐场
        ///	&quot;2334&quot;: {
        ///	 &quot;name&quot;: &quot;人造精霊の再調整&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;3088&quot;: {
        ///	 &quot;name&quot;: &quot;再演の叙事詩&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;167&quot;: {
        ///	 &quot;name&quot;: &quot;四国合同演習&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;173&quot;: {
        ///	 &quot;name&quot;: &quot;レグラ・ヴァン・ヒュドルス追撃戦&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;179&quot;: {
        ///	 &quot;name&quot;: &quot;宝物庫 アクアポリス&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_JA_JP {
            get {
                return ResourceManager.GetString("Data_JA_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // 버전
        ///  &quot;version&quot;: &quot;20181118.1&quot;,
        ///
        ///  // 임무
        ///  &quot;instances&quot;: {
        ///    // 2.0 신생 에오르제아
        ///    // 2.0 던전
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;사스타샤 침식 동굴&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;브레이플록스의 야영지&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;방랑자의 궁전&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;구리종 광산&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_KO_KR {
            get {
                return ResourceManager.GetString("Data_KO_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181204.1&quot;, 
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///	//单人使命 PVP 金碟游乐场
        ///	&quot;2334&quot;: {
        ///	 &quot;name&quot;: &quot;重新调整人造元灵&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;3088&quot;: {
        ///	 &quot;name&quot;: &quot;回顾英雄诗篇&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;167&quot;: {
        ///	 &quot;name&quot;: &quot;四国联合军演&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;173&quot;: {
        ///	 &quot;name&quot;: &quot;雷古拉·范·休著斯追击战&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;179&quot;: {
        ///	 &quot;name&quot;: &quot;水城宝物库&quot;,
        ///	 &quot;tank&quot;: &quot;0&quot;,
        ///	 &quot;healer&quot;: &quot;0&quot;,
        ///	 &quot;dps&quot;: &quot;0&quot;
        ///	},
        ///	&quot;181&quot;: {
        ///	 &quot;name&quot;: [字符串的其余部... 的本地化字符串。
        /// </summary>
        internal static string Data_ZH_CN {
            get {
                return ResourceManager.GetString("Data_ZH_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;Duty/FATE Notificator&quot;,
        ///  
        ///  &quot;tts-langset&quot;: &quot;en&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;Unknown Duty ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;Unknown Roulette ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;Unknown Area ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;Unknown FATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;Version {0} Updated&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; Matched!&quot;,
        ///  &quot;notification-update-enabled&quot;: &quot;Updateable to {0}&quot;,
        ///  &quot;notification-uptodate&quot;: &quot;Updating to {0}&quot;,
        ///  &quot;notification-update-latest&quot;: &quot;Already the latest version&quot;,
        ///  &quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_EN_US {
            get {
                return ResourceManager.GetString("Localization_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;Notificateur Mission/ALEA&quot;,
        ///  
        ///  &quot;tts-langset&quot;: &quot;fra&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;Mission inconnue ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;Mission aléatoire inconnue ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;Zone inconnue ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;ALEA inconnu ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;Mise à jour version {0}&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; disponible!&quot;,
        ///  &quot;notification-update-enabled&quot;: &quot;mises à la {0}&quot;,
        ///  &quot;notification-uptodate&quot;: &quot;la mise à jour de la {0}&quot;,
        ///  &quot;notification-update-latest&quot;:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_FR_FR {
            get {
                return ResourceManager.GetString("Localization_FR_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;Duty/FATE Notificator&quot;,
        ///  
        ///  &quot;tts-langset&quot;: &quot;jp&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;不明なコンテンツ ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;不明なルーレット ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;不明なエリア ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;不明なFATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;バージョン {0} に更新されました&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 突入準備完了!&quot;,
        ///  &quot;notification-update-enabled&quot;: &quot;Updateable to {0}&quot;,
        ///  &quot;notification-uptodate&quot;: &quot;Updating to {0}&quot;,
        ///  &quot;notification-update-latest&quot;: &quot;Already the latest version&quot;,
        ///  &quot;notification-dll-missing&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_JA_JP {
            get {
                return ResourceManager.GetString("Localization_JA_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;임무/돌발 찾기 도우미&quot;,
        ///  
        ///  &quot;tts-langset&quot;: &quot;kor&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;알 수 없는 임무 ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;알 수 없는 무작위 임무 ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;알 수 없는 지역 ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;알 수 없는 돌발 ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;버전 {0} 업데이트됨&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 매칭!&quot;,
        ///  &quot;notification-update-enabled&quot;: &quot;{0} 까지 업데이트할 수 있어요&quot;,
        ///  &quot;notification-uptodate&quot;: &quot;{0} 를 업데이트하고 있습니다&quot;,
        ///  &quot;notification-update-latest&quot;: &quot;최신 버전을 이용중입니다&quot;,
        ///  &quot;notification-dll-missing&quot;: &quot;Missing compon [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_KO_KR {
            get {
                return ResourceManager.GetString("Localization_KO_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;任务/FATE 助手 - DFA&quot;,
        ///
        ///  &quot;tts-langset&quot;: &quot;zh&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;未知任务 ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;未知随机任务 ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;未知地区 ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;未知FATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;已更新至版本 {0} &quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 匹配完成！&quot;,
        ///  &quot;notification-update-enabled&quot;: &quot;可更新至新版本 {0}&quot;,
        ///  &quot;notification-uptodate&quot;: &quot;正在更新至版本 {0}&quot;,
        ///  &quot;notification-update-latest&quot;: &quot;更新检查完成，暂无更新&quot;,
        ///  &quot;notification-dll-missing&quot;: &quot;缺失组件[{0}]，正在联网获取&quot;,
        ///  &quot;notification-dll-invalid&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_ZH_CN {
            get {
                return ResourceManager.GetString("Localization_ZH_CN", resourceCulture);
            }
        }
    }
}
