//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20180922.1&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;Sastasha&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;Brayflox&apos;s Longstop&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;The Wanderer&apos;s Palace&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;Copperbell Mines&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_EN_US {
            get {
                return ResourceManager.GetString("Data_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181008.6&quot;, 
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;Sastasha&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;le Bivouac de Brayflox&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;le Palais du Vagabond&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;les Mines de Clochecuivre&quot;,
        ///      &quot;tan [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_FR_FR {
            get {
                return ResourceManager.GetString("Data_FR_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181008.6&quot;, 
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;天然要害 サスタシャ浸食洞&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;奪還支援 ブレイフロクスの野営地&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;旅神聖域 ワンダラーパレス&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;封鎖坑道 カッパーベル銅山&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;heale [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_JA_JP {
            get {
                return ResourceManager.GetString("Data_JA_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // 버전
        ///  &quot;version&quot;: &quot;20181008.6&quot;, 
        ///
        ///  // 임무
        ///  &quot;instances&quot;: {
        ///    // 2.0 신생 에오르제아
        ///    // 2.0 던전
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;사스타샤 침식 동굴&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;브레이플록스의 야영지&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;방랑자의 궁전&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;구리종 광산&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;7&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_KO_KR {
            get {
                return ResourceManager.GetString("Data_KO_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181010.2&quot;, 
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///	// 金碟游乐场
        ///    &quot;195&quot;: {
        ///      &quot;name&quot;: &quot;九宫幻卡：幻卡对局室&quot;,
        ///      &quot;tank&quot;: &quot;0&quot;,
        ///      &quot;healer&quot;: &quot;0&quot;,
        ///      &quot;dps&quot;: &quot;0&quot;
        ///    },
        ///    &quot;197&quot;: {
        ///      &quot;name&quot;: &quot;萌宠之王：玩家对战（绩点赛）&quot;,
        ///      &quot;tank&quot;: &quot;0&quot;,
        ///      &quot;healer&quot;: &quot;0&quot;,
        ///      &quot;dps&quot;: &quot;0&quot;
        ///    },
        ///    &quot;199&quot;: {
        ///      &quot;name&quot;: &quot;萌宠之王：玩家对战（无绩点赛）&quot;,
        ///      &quot;tank&quot;: &quot;0&quot;,
        ///      &quot;healer&quot;: &quot;0&quot;,
        ///      &quot;dps&quot;: &quot;0&quot;
        ///    },
        ///    &quot;576&quot;: {
        ///      &quot;name&quot;: &quot;萌宠之王：讨伐级单人战&quot;,
        ///      &quot;tank&quot;: &quot;0&quot;,
        ///      &quot;healer&quot;: &quot;0&quot;,
        ///      &quot;dps&quot;: &quot;0&quot;
        ///    },
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_ZH_CN {
            get {
                return ResourceManager.GetString("Data_ZH_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;Duty/FATE Notificator&quot;,
        ///  
        ///  &quot;tts-langset&quot;: &quot;en&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;Unknown Duty ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;Unknown Roulette ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;Unknown Area ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;Unknown FATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;Version {0} Updated&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; Matched!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; FATE Occured!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; Matched!&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;Book of Skyfire I&quot;,
        ///  &quot;fate-prese [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_EN_US {
            get {
                return ResourceManager.GetString("Localization_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;Notificateur Mission/ALEA&quot;,
        ///  
        ///  &quot;tts-langset&quot;: &quot;fra&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;Mission inconnue ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;Mission aléatoire inconnue ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;Zone inconnue ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;ALEA inconnu ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;Mise à jour version {0}&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; disponible!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;ALEA &lt; {0} &gt; en cours!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; disponible!&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;Bo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_FR_FR {
            get {
                return ResourceManager.GetString("Localization_FR_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;Duty/FATE Notificator&quot;,
        ///  
        ///  &quot;tts-langset&quot;: &quot;jp&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;不明なコンテンツ ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;不明なルーレット ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;不明なエリア ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;不明なFATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;バージョン {0} に更新されました&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 突入準備完了!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; FATE発生!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; 突入準備完了!&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;炎天一巻&quot;,
        ///  &quot;fate-preset-animus-SkyfireII&quot;: &quot;炎天二巻&quot;,
        ///  &quot;fate-preset-a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_JA_JP {
            get {
                return ResourceManager.GetString("Localization_JA_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;임무/돌발 찾기 도우미&quot;,
        ///  
        ///  &quot;tts-langset&quot;: &quot;kor&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;알 수 없는 임무 ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;알 수 없는 무작위 임무 ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;알 수 없는 지역 ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;알 수 없는 돌발 ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;버전 {0} 업데이트됨&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 매칭!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; 돌발 발생!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; 매칭!&quot;,
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;불의 서 1권&quot;,
        ///  &quot;fate-preset-animus-SkyfireII&quot;: &quot;불의 서 2권&quot;,
        ///  &quot;fate-preset-animus-N [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_KO_KR {
            get {
                return ResourceManager.GetString("Localization_KO_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;任务/FATE 助手 - DFA&quot;,
        ///
        ///  &quot;tts-langset&quot;: &quot;zh&quot;,
        ///
        ///  &quot;unknown-instance&quot;: &quot;未知任务 ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;未知随机任务 ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;未知地区 ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;未知FATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;已更新至版本 {0} &quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 匹配完成！&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;FATE &lt; {0} &gt; 出现！&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;匹配到 &lt; {0} &gt;&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;炎天一卷&quot;,
        ///  &quot;fate-preset-animus-SkyfireII&quot;: &quot;炎天二卷&quot;,
        ///  &quot;fate-preset-animus-NetherfireI&quot;: &quot;炎狱一卷&quot;,
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_ZH_CN {
            get {
                return ResourceManager.GetString("Localization_ZH_CN", resourceCulture);
            }
        }
    }
}
